### ISSUE TITLE
IamportHttpClient testability 문제

### ISSUE THREAD

**Issue by gongdo** [gongdo/iamport-rest-client-net#13]
`IamportHttpClient`가 내부적으로 사용하는 `HttpClient`가 `Authorize `호출 후 `DefaultHeaders`에 토큰 헤더를 갖는지 여부를 유닛 테스트할 수 없습니다.

Dummy-server 또는 E2E로 테스트할 수 있지만 구조를 적절히 변경하여 E2E 없이 테스트할 수 있도록 하는게 적당하지 않을지 검토가 필요합니다.

**Comment by jwChung** [comment]
`HttpClient`를 가지는 생성자 오버로드로 해결하면 어떨까요? 물론 이때는 `HttpClient`를 독점적으로 소유하고 있지 않으므로 `Dipose`하는 건 맞지 않겠네요. 

```
private readonly bool ownsExclusively;
public IamportHttpClient(IOptions<IamportHttpClientOptions> optionsAccessor)
    :this(optionsAccessor, new HttpClient())
{
    this.ownsExclusively = true;
}

public IamportHttpClient(IOptions<IamportHttpClientOptions> optionsAccessor, HttpClient httpClient)
{
    this.HttpClient = httpClient; 
    this.HttpClient.BaseAddress = new Uri(options.BaseUrl, UriKind.Absolute);
    this.HttpClient.DefaultRequestHeaders.Connection.Add("keep-alive");
    ...
}

public HttpClient HttpClient { get; }

public void Dispose()
{
    if(this.ownsExclusively)
        this.httpClient
}
```

**Comment by gongdo** [comment]
@jwChung 의견감사합니다.
곰곰히 생각해봤는데 현재 클라이언트가 인증된 상태인지 여부만 별도로 노출하는 것이 좋을 것 같습니다.  `IamportHttpClient`가 `IsAuthorized`속성정도로 제공하면 되겠지요.

`HttpClient`를 직접 노출하는 것은 사용자코드에서 의도하지 않은 변경을 가할 수 있어서 피하고 싶습니다.
