### ISSUE TITLE
DLL 참조 에러

### ISSUE THREAD

**Issue by JaesunSim** [gongdo/iamport-rest-client-net#60]
안녕하세요.

우선 ASP.net 사용하여 결제 관련 페이지를 개발중에 있습니다.

닷넷은 4.5.1버전 사용중이며 , 패키지는 설치하여 DLL 파일들(Iamport.RestApi.dll, Newtonsoft.Json.dll)이 포함되어있습니다.

컴파일을하면 문제없이 컴파일이 완료됩니다.

하지만 페이지 접속시 dll 참조 에러가 납니다.

![default](https://user-images.githubusercontent.com/45749694/49713404-dccee380-fc8b-11e8-9717-640812d2ab77.JPG)

 도움부탁드립니다.

감사합니다.

**Comment by gongdo** [comment]
@JaesunSim 지금 보여주신 캡쳐 메시지를 보면 .NET Framework가 4.0 버전이네요.
아마도 배포한 서버의 .NET Framework 버전이 낮은 것 같습니다.
이 프로젝트는 개발자의 정신건강을 위해 .NET 4.0 지원을 포기했습니다. (ㅠㅠ)

**Comment by JaesunSim** [comment]
DLL 참조는 해결이 되었습니다. 감사합니다.
한가지 더 궁금한점이있습니다.
ASP.net은 결제방식이 두가지가 있더라고요. 
현재 아임포트에 결제 DEMO는 결제플러그인방식인지 , 비인증API 결제인지 궁금합니다.

**Comment by jangbora** [comment]
DEMO : https://www.iamport.kr/demo 를 말씀하신 것 같습니다. 

PG사에서 제공하는 결제창이 브라우저를 통해 직접 나타나 결제진행되므로, README에 표현된 결제플러그인 방식입니다. 

1. PrepareAsync 로 결제될 정보를 미리 등록해 위변조를 사전 방지
2. javascript 에서 IMP.request_pay() 함수 호출하여 결제창 띄워 진행
3. 결제가 끝나면 GetByIamportIdAsync 혹은 GetByTransactionIdAsync 로 결제완료 정보 조회하여 DB기록

의 순서로 진행한다고 보시면 될 것 같습니다.

**Comment by JaesunSim** [comment]
https://www.iamport.kr/demo  과 같이 구현에있습니다. ASP.net으로 구현하고있고

버튼안에 기능을 만들었습니다.

protected void Button1_Click(object sender, EventArgs e)
{
             var options = new IamportHttpClientOptions
             {
                ApiKey = "3370751080374820",
                ApiSecret = 
 "crZP9rztQlxDSFEHLZqfREky6vbMw80IAZyJr7dhtLVlqz3bytrp8MXfh91Nh2wS24CucPLFBH11g4dP",
                IamportId = "imp64166092"
            };
            var httpClient = new IamportHttpClient(options);
            var paymentsApi = new PaymentsApi(httpClient);

            // 지정한 거래 ID와 금액을 아임포트에 등록합니다.
            // 등록된 거래 ID는 반드시 동일한 금액만 결제되도록 보장합니다.
            await paymentsApi.PrepareAsync(new PaymentPreparation
            {
                Amount = 1000,
                TransactionId = "1234567890"
            });
        }
구현을 해놨지만  await paymentsApi.PrepareAsync(new PaymentPreparation
![image](https://user-images.githubusercontent.com/45749694/49849132-842e5080-fe1b-11e8-8783-534ae55d0d1b.png)

비동기메소드에서 사용이 가능하여 버튼안에서 사용하면 에러가 납니다.

조언좀 부탁드리겠습니다.

**Comment by gongdo** [comment]
@JaesunSim 이 프로젝트는 모던한 C# 환경을 지향하여 모든 네트워크 접근은 비동기 async/await를 사용합니다. 아마도 ASP.NET Forms 환경일 것 같은데, 이 경우 서버사이드의 이벤트 핸들러를 다음과 같이 비동기 메서드로 만들어주면 됩니다.
```
// 반드시 async 키워드 필요
protected async void Button1_Click(object sender, EventArgs e) {
  // 반드시 await 키워드로 비동기 메서드 호출 필요
  await subscribeApi.DoDirectPaymentAsync(request);
}
```

이 외에도 다양한 방법이 있는데 자세한 내용은 MSDN 등에서 ASP.NET 개발 문서를 찾아보시길 바랍니다.
https://docs.microsoft.com/en-us/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45

이 이슈는 해결된 것 같습니다. 추가적인 질문이 있다면 새 이슈로 올려주세요.
